---
title: "mbta"
author: "Huifei Xu 63205581"
date: "2022-12-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# environment

```{r}
library(readr)
library(dplyr)
```



# import dataset

```{r}
stop <- read_csv("stops.txt")
r1 <- read_csv("HRTravelTimesQ4_21.csv")
l1 <- read_csv("LRTravelTimesQ4_21.csv")
```

# table for number of station
```{r}
n_station <- rbind(select(r1,c(3,4)),select(l1,c(3,4))) %>% unique() %>% count(route_id)
```

# Histogram
```{r}
mycolor = c("blue","chartreuse","chartreuse1","chartreuse2","chartreuse3","cyan","orange","red")

his_station <- barplot(height=n_station$n, names=n_station$route_id, col=mycolor,
        xlab="Main Subway Lines", 
        ylab="Counts", 
        main="Count of stations per MBTA line", 
        ylim=c(0,55) )
```

# test

# produce geo dataframe


```{r}

r_station <- rbind(select(r1,c(3,4)),select(l1,c(3,4))) %>% unique()
```

```{r}
mstop <-select(stop,c("stop_id","stop_lat","stop_lon","platform_name"))

b <- as.character(r_station$to_stop_id)
ans = stop[which(mstop$stop_id ==b[1]),]

for (i in 1:length(r_station$to_stop_id)){
  mt <- stop[which(mstop$stop_id ==b[i]),]
  ans = rbind(mt,ans)
}

mt <- select(ans[1:length(r_station$to_stop_id),],nacol)
mt$stop_id <- as.numeric(mt$stop_id)
mt <- mt[order(mt$stop_id),]
mt$line <- as.factor(r_station$route_id)

```

# map fig
```{r}
ggplot(data = world) +
    geom_sf(fill = "cornsilk") +
  
      geom_sf(data = counties, fill = NA, color = gray(.5)) +
  
    geom_point(data = mt, aes(x = stop_lon, y = stop_lat,color = line), size = 0.65
         ) +

       annotate(geom = "text", x = -71.1, y = 42.16, label = "Norfalk", 
         color = "grey22", size = 4.5) +
    
         annotate(geom = "text", x = -71.15, y = 42.45, label = "Middlesex", 
         color = "grey22", size = 4.5) +
  
           annotate(geom = "text", x = -70.98, y = 42.47, label = "Essex", 
         color = "grey22", size = 4.5) +
  
             annotate(geom = "text", x = -70.88, y = 42.14, label = "Plymouth", 
         color = "grey22", size = 4.5) +

  
    coord_sf(xlim = c(-71.3, -70.8), ylim = c(42.1, 42.5), expand = FALSE) +
  scale_color_manual(values=mycolor)
```







```{r}

df <- rbind(select(r1,c(3,4)),select(l1,c(3,4))) %>% unique()
r_station <- df %>% unique()

nacol <- c("stop_id","stop_lat","stop_lon","platform_name")
mstop <-select(stop,nacol)

b <- as.character(r_station$to_stop_id)
ans = stop[which(mstop$stop_id ==b[1]),]

-
for (i in 1:length(r_station$to_stop_id)){
  mt <- stop[which(mstop$stop_id ==b[i]),]
  ans = rbind(mt,ans)
}
ans <- ans[1:103,]
mt <- select(ans,nacol)
mt$stop_id <- as.numeric(mt$stop_id)
mt <- mt[order(mt$stop_id),]
mt$line <- r_station$route_id
mt
```




```{r}
library(ggplot2)
theme_set(theme_bw())
library(sf)

library("rnaturalearth")
library("rnaturalearthdata")

world <- ne_countries(scale = "medium", returnclass = "sf")

```

```{r}
ggplot(data = world) +
    geom_sf(fill = "cornsilk") +
  
      geom_sf(data = counties, fill = NA, color = gray(.5)) +
  
    geom_point(data = mt[mt$line == "Blue",], aes(x = stop_lon, y = stop_lat), size = 0.65, 
         color = "blue") +
    geom_line(data = mt[mt$line == "Blue",],aes(x = stop_lon,y = stop_lat),color = "blue",alpha = 0.6) +
  
    geom_point(data = mt[mt$line == "Orange",], aes(x = stop_lon, y = stop_lat), size = 0.65, 
         color = "orange")+
      # geom_line(data = mt[mt$line == "Orange",],aes(x = stop_lon,y = stop_lat),color = "orange") +

  
      geom_point(data = mt[mt$line == "Red",], aes(x = stop_lon, y = stop_lat), size = 0.65, 
         color = "red") +
       # geom_line(data = mt[mt$line == "Red",],aes(x = stop_lon,y = stop_lat),color = "red") +
  
       annotate(geom = "text", x = -71.1, y = 42.16, label = "Norfalk", 
         color = "grey22", size = 4.5) +
    
         annotate(geom = "text", x = -71.15, y = 42.45, label = "Middlesex", 
         color = "grey22", size = 4.5) +
  
           annotate(geom = "text", x = -70.98, y = 42.47, label = "Essex", 
         color = "grey22", size = 4.5) +
  
             annotate(geom = "text", x = -70.88, y = 42.14, label = "Plymouth", 
         color = "grey22", size = 4.5) +

  
    coord_sf(xlim = c(-71.3, -70.8), ylim = c(42.1, 42.5), expand = FALSE)
```

```{r}
library("tools")
library("maps")
counties <- st_as_sf(map("county", plot = FALSE, fill = TRUE))
counties <- subset(counties, grepl("massachusetts", counties$ID))
counties$area <- as.numeric(st_area(counties))
```










# ggmap

```{r}

# Base layer
leaflet() %>%
# Base map
  addTiles() %>% 
# Centering view on the following coordinates and zooming in.
  setView(lng = -71.0589, lat = 42.3601, zoom = 12)
```
